### ISSUE TITLE
Relative paths not building

### ISSUE THREAD

**Issue by wekempf** [cake-contrib/Cake.DocFx#10]
I have a project that uses the following in its index.md file.

```[!code-csharp[Inclusion](..\src\Examples\Testify.Examples\Inclusion.cs#L1-L2)]```

When building outside of Cake this works correctly. When I run it inside of Cake with the following code it fails.

```
var settings = new DocFxSettings {
    WorkingDirectory = "./docs"
};
DocFx(settings);
```

This results in the following build warning.

```Warning: [Build Document.Save](docs/index.md)Invalid file link(~/../src/Examples/Testify.Examples/Inclusion.cs)```

The resultant index.html file does not have the appropriate code inserted. My assumption is that the relative path is what's causing problems here, though that's just an educated guess.

**Comment by reicheltp** [comment]
Hi @wekempf,

I tried to reproduce this, but I have no clue, how you run into this problem. Can you provide a simple project where this issue is reproduces?

I have also created a simple working example you may like to checkout: https://github.com/reicheltp/cake-docfx-sample

**Comment by wekempf** [comment]
Sorry for the delay in responding. The best way to show you what's happening is with the actual project, since it's open source, but I had to finish up the changes I was making to switch to a Cake build process, and I was busy with other things. :)

The repo is at https://github.com/wekempf/testify. You can view the build logs at https://ci.appveyor.com/project/wekempf/testify/build/1.0.51. I made a mistake here. Building using docfx.exe was working perfectly when I opened this issue, but right afterwards I upgraded to the latest version (2.7.3), which produces 12 warnings now. I'm uncertain which version I was using when it built clean, but regardless these 12 warnings are different and unrelated to the warning from the Cake build (they are all warnings about ValidateBookmark failures... the rapid changes to DocFX, often "breaking" changes, is killing me). Given the unstable nature of DocFX itself right now, this whole issue might be something related to the specific DocFX version used by the Cake tools here, and not with the Cake tools themselves, but I don't know how to verify that easily.

**Comment by reicheltp** [comment]
@wekempf I like that we can give the fault to DocFx 😏 

Nevertheless, if you've found a working version you can stick on them until you found the next one with:
`#tool nuget:?package=docfx.msbuild&version=1.2.3`

For now I close this until someone can identify that the fault is by this add-in.

**Comment by wekempf** [comment]
Disappointed this was closed without any investigation. I do NOT know that this is a DocFX version issue.

I've been trying to play around with different versions. New to Cake, and I found that confusing. Using your ```#tool``` syntax I wasn't seeing any difference. So, I commented it out and found it still didn't make a difference. I deleted the tools directory and now found that the script used the docfx.exe installed in the system, rather than one from tools. Crazy, IMHO, but not relevant to you or this project.

Anyway, by blowing away tools and changing the version in the ```#tool``` directive I was able to test all the way back to 2.0.0, and every version has the same issue. The behavior really is as if the working directory isn't set, so that the relative path isn't accurate. Yes, I'm speculating. In any case, the fact that it fails with all of these versions is an indication it's probably not in DocFX. I'm willing to help figure out what the issue is, and blame the right party (Cake, DocFX or Cake.DocFX) but having never written a Cake addin, I have no idea how to go about debugging.

**Comment by wekempf** [comment]
BTW, I did find this: https://github.com/dotnet/docfx/issues/839. Maybe we should be using docfx.console instead of docfx.msbuild in scripts here?

**Comment by wekempf** [comment]
LOL - success. The DocFX.exe version used when following the documentation here, which says to use ```#tool docfx.msbuild``` is evidently too damn old. By switching to use docfx.console I now get the same result as I do from the command line (too many warnings about ValidateBookmark failing, but none for the relative link, and the final generated documentation is correct). I even uninstalled DocFX from my system to be sure the script uses the binary from docfx.console.

You need to update the readme.md and any other documentation, but my issue is resolved. I have an issue to open with the DocFX folks, though. :(

**Comment by reicheltp** [comment]
Thanks @wekempf for the hint with the deprecated version. 

Currently, I barely use docfx so I did not run into this issue by myself.
