### ISSUE TITLE
Additional Maintainer

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.DocFx#25]
@reicheltp would you have any objections to be adding @pascalberger as a maintainer on this project?

He is actively using the addin for a number of his projects, and is interested in adding additional functionality to cover different use cases.

Thanks

**Comment by reicheltp** [comment]
@gep13  Sure 😄 
@pascalberger Welcome on board. Is Write Access sufficient? Or better Admin Access?

**Comment by pascalberger** [comment]
@reicheltp If possible I would prefer admin access, but whatever you feel more comfortable with is fine for me.

**Comment by gep13** [comment]
@reicheltp if it is ok with you, I will add this through the Team Settings, rather than directly on the repository.  This makes it easier to pass permissions through to AppVeyor, etc.

**Comment by gep13** [comment]
@reicheltp actually, looks like you have the required access to do this.  Good to know! 👍

**Comment by reicheltp** [comment]
@pascalberger Admin is fine as well. I've changed the privileges.

**Comment by pascalberger** [comment]
@reicheltp Are you OK if I merge the PRs (eg #20 and #21) or do you want to review them all first?

**Comment by reicheltp** [comment]
@pascalberger I am totally fine, letting you decide to merge PRs. No need of approvals on my side.
