### ISSUE TITLE
Move different subcommands to individual namespaces

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.DocFx#33]
To make future enhancements easier the code for the different subcommands should be moved to their own namespaces.

**Comment by pascalberger** [comment]
This is essentially a revert of #3, but this time also adding [CakeNamespaceImportAttribute](http://cakebuild.net/api/Cake.Core.Annotations/CakeNamespaceImportAttribute/).

**Comment by pascalberger** [comment]
@reicheltp Would you be OK with this change? IMHO it shouldn't break anything in practice as long as the settings classes are used together with their corresponding alias.

**Comment by reicheltp** [comment]
@pascalberger sure let's do this

**Comment by pascalberger** [comment]
@reicheltp 👍 After merging these two open issues I would like to release a 0.3.0. Or do you have anything else which should get into this release?
