### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by agc93** [cake-contrib/Cake.DocFx#42]
This tool should be able to support .NET Standard 1.6 (and also the new VS 2017 tooling) without too many changes.

This is blocked by [cake-contrib/Cake.Recipe#10](https://github.com/cake-contrib/Cake.Recipe/issues/10).

*Raising this for tracking until that is resolved*

**Comment by secana** [comment]
Hi, the ticket you referenced as blocking is resolved. It would be awesome if you could add .Net Standard support to the Cake.DocFx.
