### ISSUE TITLE
Ensure CI build is still working

### ISSUE THREAD

**Issue by reicheltp** [cake-contrib/Cake.DocFx#6]

**Comment by gep13** [comment]
@reicheltp we should actually figure out how to get the build of this project, and your other repositories, into the cake-contrib project on AppVeyor, so that all the builds are in the same place.  I haven't had time to sit down in AppVeyor and figure out how to bring through the GitHub teams that I have set up, and map them onto AppVeyor roles.  Definitely need to do this sooner rather than later.

**Comment by reicheltp** [comment]
@gep13 How is the progress with this? Is there anything I can help you?

**Comment by gep13** [comment]
I think I have this figured out, but I just have one last thing I need to figure out.

I have done the following:

* Added a Role in AppVeyor for each addin that currently exists in the Cake-Contrib Repo
* Allocated the necessary permissions to each Role

Now what I need to do is assign the GitHub Teams to these roles, however, I have a concern about this:

![image](https://cloud.githubusercontent.com/assets/1271146/19359618/d0c3af02-9172-11e6-9601-45ed78264d6c.png)

I am not sure what Inherit means in this case.  I don't know if I need to explicitly Allow/Deny each Role to each project that they are meant to be in, or if a Role only gets access if they are explicitly allowed.

@FeodorFitsner @IlyaFinkelshteyn can either of you comment on exactly what I need to do here?  I want the Cake.DocFx Role to "only" have permission to the Cake.DocFx project, and no others.  Do I need to go through each AppVeyor Project and Deny this Role on each Project?  Thanks!

**Comment by reicheltp** [comment]
@gep13 Do we really need to have access to AppVeyor itself? Nearly everything can be configured via `appveyor.yml`. The build status and logs are public in any case.

**Comment by gep13** [comment]
It is not "required", however, part of the initial push back we heard when we suggested the cake-contrib repo was that people didn't want to "lose" anything by moving the repo into the organisation.  As a result, I want to know that I "can" allow people to do everything, as if it was their own project :smile:

**Comment by gep13** [comment]
@reicheltp in any event, for now, here is the project:  

https://ci.appveyor.com/project/cakecontrib/cake-docfx

**Comment by FeodorFitsner** [comment]
"Inherit" means "inherit permissions from the role". Default permission is to view all projects, so yes you should go through all projects and explicitly "deny" them for specific role(s).

**Comment by gep13** [comment]
@FeodorFitsner okay, that is what I thought, thanks!

**Comment by gep13** [comment]
The AppVeyor CI Build is now up and running on the cake-contrib account.
