### ISSUE TITLE
Build against Cake 0.26.0

### ISSUE THREAD

**Issue by sdanyliv** [cake-contrib/Cake.DocFx#60]
Hi,
There is new Cake version that requires updating Cake.DocFx package.

Thanks!

**Comment by fleed** [comment]
Any ETA for verifying the PR and publishing it?

**Comment by pascalberger** [comment]
New version is currently building and should soon be available on nuget.org

**Comment by sdanyliv** [comment]
Thanks for that!

**Comment by fleed** [comment]
Thank you @pascalberger , it works perfectly
