### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.DocFx#62]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [x] You are currently referencing Cake.Core 0.26.0. Please upgrade to 0.28.0
- [x] The Cake.Core reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Core" Version="0.28.0" PrivateAssets="All" />`
- [x] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by pascalberger** [comment]
The second point is not an issue here as a nuspec file is used

**Comment by Jericho** [comment]
When this issue was created a few weeks ago, the audit tool parsed the .csproj and was not aware of nuspec files which could lead to false-positives in some cases, such as the one you pointed out. This is no longer the case as we now parse the metadata in the package that we download from nuget.org 

If you look at the daily report generated by the audit tool, you should find it more accurate.
