### ISSUE TITLE
DocFxInitSettings could not be found

### ISSUE THREAD

**Issue by boebeng** [cake-contrib/Cake.DocFx#63]
I am using Cake.DocFx 0.6.0 and it seems the the namespace 'Cake.DocFx.Init' is not be initialized by Cake
I need to give the whole namespace for DocFxInit otherwise I get a compilation error

This works:
DocFxInit(new Cake.DocFx.Init.DocFxInitSettings()
{
 OutputPath = "tmp"
});

**Comment by pascalberger** [comment]
Thanks for reporting this. This is a bug in the namespace import for the [DocFxInit alias](https://github.com/cake-contrib/Cake.DocFx/blob/develop/src/Cake.DocFx/DocFxInitAliases.cs#L13)
