### ISSUE TITLE
Issue when running on VSTS build agent

### ISSUE THREAD

**Issue by fleed** [cake-contrib/Cake.DocFx#72]
Hi

I'm using the library (version `0.8.0`) and it works perfectly on my computer.
Running it on the VSTS build agent I get the following error:

```
Could not load E:\agent\_work\22\s\tools\Addins\Cake.DocFx.0.8.0\lib\netstandard2.0\Cake.DocFx.dll (missing netstandard,
 Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
```

On both computers, I have installed at least .NET 4.6.1. The only difference is that my computer is a Windows 10 machine, while the agent runs Windows Server2012 R2.

I tried with the version `0.6.0` and it works. What could be the problem?

**Update**: it works after installing `.net 4.7.1` on the server

**Comment by pascalberger** [comment]
@fleed .NET 4.6.1 contains a bug leading to this. So if you can go to .NET 4.7.x this would be the proper solution for this as there's nothing we can do from the addin side.

**Comment by Lakritzator** [comment]
Thanks for this information, I've been going made due to this issue!!

**Comment by pascalberger** [comment]
@Lakritzator See https://twitter.com/terrajobst/status/1031999730320986112
